### ISSUE TITLE
 WCClientException("settlement timeout") with Stellar Blockchain

### ISSUE THREAD

**Issue by garantor** [bitlogik/pyWalletConnect#5]
Hi @bitlogik great job with the launch of wallet connect V2, I tried it out and it connects flawlessly with  [walletConnect official demo wallet](https://react-app.walletconnect.com/) but I get a settlement timeout Error when trying to connect to Stellar Blockchain, I get the below error when I enabled the debugger. I am using the demo you provide plus [Stellarx](https://www.stellarx.com/login) or [stellarterm](https://stellarterm.com/wallet-connect/)

`Paste a Dapp WC URI (v1 or v2) >wc:9e2a21a0a45dd69f0dde28eb006644d70854e5070916a5b75ef78dbecddb519e@2?controller=false&publicKey=ec402b5fe1ead64589eabb3630662d977a9676c3324ffd8415424f8fc737c015&relay=%7B%22protocol%22%3A%22waku%22%7D
DEBUG:pyWalletConnect.pywalletconnect.client:URI WC version 2 decoding
DEBUG:pyWalletConnect.pywalletconnect.client:wc v2 URI provided decoded successfully, now starting the WalletConnect client
DEBUG:pyWalletConnect.pywalletconnect.client:Opening a WalletConnect v2 client with https://relay.walletconnect.com/?env=desktop&projectId=e397e5f559a140a795d5efd71f7a8b88&protocol=wc&version=2
DEBUG:pyWalletConnect.pywalletconnect.tls_socket:Socket connected
DEBUG:pyWalletConnect.pywalletconnect.websocket:Connecting to WebSocket Host=relay.walletconnect.com PathTarget=/?env=desktop&projectId=e397e5f559a140a795d5efd71f7a8b88&protocol=wc&version=2
DEBUG:pyWalletConnect.pywalletconnect.websocket:Waiting WebSocket handshake : 1th loop.
DEBUG:pyWalletConnect.pywalletconnect.websocket:Waiting WebSocket handshake : 2th loop.
DEBUG:pyWalletConnect.pywalletconnect.websocket:WebSocket connection established.
DEBUG:pyWalletConnect.pywalletconnect.client:wc v2 URI and project id accepted
Connecting with the Dapp ...
DEBUG:pyWalletConnect.pywalletconnect.client:Sending a subscription request for d42af0edd421bd9f58fb2b83c5292e1b9d46a418592112c989dbd77469e0d025.
DEBUG:pyWalletConnect.pywalletconnect.client:WalletConnect message sending to relay : {"jsonrpc":"2.0","id":1,"method":"waku_subscribe","params":{"topic":"d42af0edd421bd9f58fb2b83c5292e1b9d46a418592112c989dbd77469e0d025"}}
DEBUG:pyWalletConnect.pywalletconnect.client:Waiting for Topic subcription ack.
DEBUG:pyWalletConnect.pywalletconnect.client:Get Data, full messages queue : []
DEBUG:pyWalletConnect.pywalletconnect.websocket:WebSocket Text message received : {"id":1,"jsonrpc":"2.0","result":"d8b21de30d910160e28fa7b923b777bdbbe29cb1184177499546d906ee8461de"}
DEBUG:pyWalletConnect.pywalletconnect.client:Get Data, full messages queue : ['{"id":1,"jsonrpc":"2.0","result":"d8b21de30d910160e28fa7b923b777bdbbe29cb1184177499546d906ee8461de"}']
DEBUG:pyWalletConnect.pywalletconnect.client:A message pop from the queue : {"id":1,"jsonrpc":"2.0","result":"d8b21de30d910160e28fa7b923b777bdbbe29cb1184177499546d906ee8461de"}
DEBUG:pyWalletConnect.pywalletconnect.client:Result received : d8b21de30d910160e28fa7b923b777bdbbe29cb1184177499546d906ee8461de
DEBUG:pyWalletConnect.pywalletconnect.client:<-- WalletConnect response read : d8b21de30d910160e28fa7b923b777bdbbe29cb1184177499546d906ee8461de
DEBUG:pyWalletConnect.pywalletconnect.client:Sending a publish request for 9e2a21a0a45dd69f0dde28eb006644d70854e5070916a5b75ef78dbecddb519e.
DEBUG:pyWalletConnect.pywalletconnect.client:WalletConnect message sending to relay : {"jsonrpc":"2.0","id":3,"method":"waku_publish","params":{"topic":"9e2a21a0a45dd69f0dde28eb006644d70854e5070916a5b75ef78dbecddb519e","message":"7b226a736f6e727063223a22322e30222c226964223a322c226d6574686f64223a2277635f70616972696e67417070726f7665222c22706172616d73223a7b2272656c6179223a7b2270726f746f636f6c223a2277616b75227d2c22726573706f6e646572223a7b227075626c69634b6579223a2234366664663433376363653864663938306530613135333838366632383165336133316362633532313432666134333436326234386462623662633566633464227d2c22657870697279223a313634343734393738372c227374617465223a7b226d65746164617461223a7b226465736372697074696f6e223a22707957616c6c6574436f6e6e6563742076312e322e32206279204269744c6f67694b222c2275726c223a2268747470733a2f2f6769746875622e636f6d2f6269746c6f67696b2f707957616c6c6574436f6e6e656374222c2269636f6e73223a5b2268747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6269746c6f67696b2f707957616c6c6574436f6e6e6563742f6d61737465722f6c6f676f2e706e67225d2c226e616d65223a22707957616c6c6574436f6e6e656374227d7d7d7d","ttl":86400}}
DEBUG:pyWalletConnect.pywalletconnect.client:Waiting for Pairing Approve ack.
DEBUG:pyWalletConnect.pywalletconnect.client:Get Data, full messages queue : []
DEBUG:pyWalletConnect.pywalletconnect.websocket:WebSocket Text message received : {"id":3,"jsonrpc":"2.0","result":true}
DEBUG:pyWalletConnect.pywalletconnect.client:Get Data, full messages queue : ['{"id":3,"jsonrpc":"2.0","result":true}']
DEBUG:pyWalletConnect.pywalletconnect.client:A message pop from the queue : {"id":3,"jsonrpc":"2.0","result":true}
DEBUG:pyWalletConnect.pywalletconnect.client:Result received : True
DEBUG:pyWalletConnect.pywalletconnect.client:<-- WalletConnect response read : True
DEBUG:pyWalletConnect.pywalletconnect.client:Waiting for WalletConnect settlement.
DEBUG:pyWalletConnect.pywalletconnect.client:Closing WalletConnect link.
DEBUG:pyWalletConnect.pywalletconnect.websocket:Cancelling the WebSocket reading timer
DEBUG:pyWalletConnect.pywalletconnect.websocket:Closing WebSocket
DEBUG:pyWalletConnect.pywalletconnect.tls_socket:Closing socket
Traceback (most recent call last):
  File "/Users/afolabi/projects/walletconnect/src/play.py", line 78, in <module>
    WCCLIdemo()
  File "/Users/afolabi/projects/walletconnect/src/play.py", line 30, in WCCLIdemo
    session_data = wclient.open_session()
  File "/Users/afolabi/projects/walletconnect/src/pyWalletConnect/pywalletconnect/client.py", line 572, in open_session
    raise WCClientException("settlement timeout")
pyWalletConnect.pywalletconnect.client.WCClientException: settlement timeout
DEBUG:pyWalletConnect.pywalletconnect.client:Closing WalletConnect link.
DEBUG:pyWalletConnect.pywalletconnect.websocket:Cancelling the WebSocket reading timer
`

**Comment by bitlogik** [comment]
Any news from your side? Did you contact the editor of these dapps?

**Comment by garantor** [comment]
Hi @bitlogik, I was able to find some answers on walletconnect discord server on how stellar connection works but am still finding it difficult to run the code on my local machine, here is a sample of the code that generates the Qrcode: https://gist.github.com/MarcoCiaramella/097b28e308817b2b7143d95a5e8d84f2

**Comment by bitlogik** [comment]
Stale issue. One of the latest changes d90959a, to be released in v1.5.0 allows to specify the chain namespace. This could be useful for this issue.
Closing it. Feel free to reopen for support.
